//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAP_Company_FixTech.Supplier_Votech_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Supplier_Votech_ServiceReference.IWs_Supplier_Votech")]
    public interface IWs_Supplier_Votech {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Supplier_Votech/insertPurchaseOrder", ReplyAction="http://tempuri.org/IWs_Supplier_Votech/insertPurchaseOrderResponse")]
        int insertPurchaseOrder(string name, string email, string contact, string address, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Supplier_Votech/insertPurchaseOrder", ReplyAction="http://tempuri.org/IWs_Supplier_Votech/insertPurchaseOrderResponse")]
        System.Threading.Tasks.Task<int> insertPurchaseOrderAsync(string name, string email, string contact, string address, string date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWs_Supplier_VotechChannel : EAP_Company_FixTech.Supplier_Votech_ServiceReference.IWs_Supplier_Votech, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ws_Supplier_VotechClient : System.ServiceModel.ClientBase<EAP_Company_FixTech.Supplier_Votech_ServiceReference.IWs_Supplier_Votech>, EAP_Company_FixTech.Supplier_Votech_ServiceReference.IWs_Supplier_Votech {
        
        public Ws_Supplier_VotechClient() {
        }
        
        public Ws_Supplier_VotechClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ws_Supplier_VotechClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws_Supplier_VotechClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws_Supplier_VotechClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int insertPurchaseOrder(string name, string email, string contact, string address, string date) {
            return base.Channel.insertPurchaseOrder(name, email, contact, address, date);
        }
        
        public System.Threading.Tasks.Task<int> insertPurchaseOrderAsync(string name, string email, string contact, string address, string date) {
            return base.Channel.insertPurchaseOrderAsync(name, email, contact, address, date);
        }
    }
}
